### ISSUE TITLE
Spell check not work

### ISSUE THREAD

**Issue by jboadas** [stanfieldr/ghetto-skype#131]
I am using Manjaro and installed this package from AUR.
Spell check is not working.

**Comment by trinaldi** [comment]
Just to rule out, do you have the packages responsible for the spell checking? I actually don't know for sure if it is `aspell` or `hunspell`.

**Comment by jboadas** [comment]
Yes I have both installed.

**Comment by stanfieldr** [comment]
Yea it doesn't appear to be working with AUR package in my VM either. I believe the next version of Ghetto Skype will fix your issue, but it hasn't been released yet. It looks like the Arch community made a ghetto-skype-git package, but I don't think it'll work right now because electron is flagged outdated in the AUR.

I went ahead and built you a version of 1.6 (might change when released), it's pretty stable I use it daily. If you really want to build your own snap, there's documentation in the README; otherwise, I built the snap [here](https://stanfield.it/downloads/ghetto-skype_1.6.0_amd64.snap).

You can use the snap package by first uninstalling Ghetto Skype then installing snapd:
```bash
sudo pacman -S snapd
sudo systemctl enable --now snapd
```
change directory to where you have the snap
```bash
sudo snap install --dangerous ghetto-skype_1.6.0_amd64.snap
```
