### ISSUE TITLE
How to get Item ID?

### ISSUE THREAD

**Issue by Catshy** [stanfieldr/ghetto-skype#140]
I want to know how you get these ID or classname，
"chatInputAreaWithQuotes","unseenNotifications",".send-button"...
Thanks～

**Comment by stanfieldr** [comment]
Close Ghetto Skype if it's open. Change your terminal directory to where the ghetto skype code resides. Then do this if you haven't already (you only need to do it once)
```
[u@h ghetto-skype]$ npm install
```

Then start ghetto skype by using npm start
```
[u@h ghetto-skype]$ npm start
```

When running it like this rather than installing through a package, you can use chrome dev tools. Hit Ctrl+Shift+i to toggle it.

**Comment by Catshy** [comment]
Thanks replay,
It seems a little problem on Mac.When i toggle developer tools,it doesn't work.But it works on  other electron app(like [electron-quick-start)](https://github.com/electron/electron-quick-start).

Besides,do you have any idea about catch message before displaying on the chat area ？
