### ISSUE TITLE
Ghetto Skype Icon remains red even when there are no notifications

### ISSUE THREAD

**Issue by taksan** [stanfieldr/ghetto-skype#49]
This is a bug. Even when I don't have any unread messages, the icon remains red.

**Comment by jvnn** [comment]
This could be due to a current bug in the web.skype.com itself, the notification for a new message sometimes stays active even when there are no unread messages.

Btw, @stanfieldr , big thanks for this! Just had to dump the native client recently due to problems with group chats (old p2p groups vs new cloud-based ones cause trouble with the old client).

**Comment by stanfieldr** [comment]
@jvnn Yea I had same problem, that and contacts would go offline sometimes lol

What I'm thinking is if the user opens Ghetto Skype, I can simulate clicking the currently selected contact name to get rid of the notification.

**Comment by shihrer** [comment]
I've been having the same problem.  Sending a message clears it out, so I just send a message to a bot.

**Comment by stanfieldr** [comment]
So I can't seem to reproduce the problem now, but I noticed when it was happening to me the notification count on the threads were right even though the title was wrong. I changed the code to see if any thread has a notification count instead, that should fix the problem.

**Comment by stanfieldr** [comment]
Included in [v1.4.1](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.1)
