### ISSUE TITLE
turn on/off sounds

### ISSUE THREAD

**Issue by scarf** [stanfieldr/ghetto-skype#70]
Please add the ability, at a minimum, to turn on/off skype sounds, like when a message is received, incoming call, etc.

**Comment by stanfieldr** [comment]
Are you on the latest version? There's a new setting for that in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0). Although that I think about it, it is a bit misleading because it says "Mute Skype Notification Sound" when in reality it mutes everything, I'll change that in the next version.
