### ISSUE TITLE
Alpha Linux Skype

### ISSUE THREAD

**Issue by ryancito02** [stanfieldr/ghetto-skype#73]
Open Source vs Closed Source.
Ghetto vs Official.

Who will prove the victor?

**Comment by bart00777** [comment]
Unfortunately, I think that the official; /

**Comment by andrii-zymohliad** [comment]
Could Microsoft make some special tricks for incompatibility of their web-version with unofficial clients? Is it technically possible? Sorry, if this is very stupid question, I'm not good in all this electron-based and web things.
If no, i think a lot of people will stay on Ghetto. Lot of linux users trust opensource much more than any proprietary software.

**Comment by bart00777** [comment]
The official version is strongly promoted. Very much noise they made. I was disappointed that this version unstable. I use the ghetto.

**Comment by stanfieldr** [comment]
@andrii-zymohliad They've been known to do stuff like that in the past. One area they have broke so far has been thumbnail links by going out of their way to use an unorthodox method instead of the normal way to open hyperlinks which happens to not play well with Electron. I've created a workaround, but I'd like to think this project isn't big enough for Microsoft to care about.

IMO the ghetto is better because we have more features and there are slight annoyances in the official I can't stand. Just little things, like having the ability to toggle visibility by clicking the tray icon. And I don't know if you guys feel the same way, but as a programmer, I love the freedom to just jump into the code and add/fix whatever I want. With the official, you just have to "deal with it"

**Comment by MavropaliasG** [comment]
I love Ghetto Skype

**Comment by bart00777** [comment]
is only for 64bit?

**Comment by ultravio1et** [comment]
im using ghetto at the moment because the official [new] one isn't available for 32bit systems at the moment [or might never be if they go down the chrome route]

**Comment by M1cha** [comment]
we could actually use the alpha-clients code. it's really just the same thing, just that all resources(js,css,...) are loaded from your disk instead of the skype servers.

Ofc these local versions are modified for better integration with the client's features but I think this is sth. we can implement too.

let the reverse engineering begin :P
